import './globals.css';
import React from 'react';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Football Score Board',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Football Score Board</title>
        <meta
          name="description"
          content="Football Score Board is a website that provides up-to-date scores and statistics for football matches from around the world. Stay informed about the latest scores, goals, cards, and other important events in the world of football."
        />
        <meta
          name="keywords"
          content="football, match results, football statistics, score, goals, cards, Football Score Board"
        />
        <meta name="author" content="SportRadar" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
